# Generated by Django 4.0.2 on 2022-03-26 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio_library', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_on_music',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='is_remix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='remix_on_music',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='license_tracks', to='audio_library.license'),
        ),
        migrations.AlterField(
            model_name='track',
            name='user_of_likes',
            field=models.ManyToManyField(blank=True, related_name='likes_of_tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
